baseURL: http://www.farseer.vip
languageCode: zh-CN
title: Snow Wang
theme: hugo-refresh # using hugo-refresh theme

disableKinds: ["sitemap","RSS"]

blackfriday:
  hrefTargetBlank: true

Taxonomies:
  tag: "tags"

# Supported fonts are:
# https://fonts.google.com/

# Icons taken from:
# https://konpa.github.io/devicon/
# https://bulkitv2.cssninja.io/_components-icons-fa.html

params:
  # parameter used to specify if you want to minify the imported js
  jsMinify: false
  # parameter used to specify if you want to add the fingerprint to the imported js
  jsFingerprint: false
  # parameter used to specify if you want to minify the imported css
  cssMinify: true
  # parameter used to specify if you want to add the fingerprint to the imported css
  cssFingerprint: true
  # option to specify the main colour of the theme
  mainColour: "#F39200"

  # summary options
  summary:
    # option to specify the default image in the summary list
    defaultImage : "/images/default_summary.jpg"
  
  # loading options
  loading:
    # option to specify the loading image
    image: "/images/loaders/rings.svg"

  # main pages options
  mainPage:
    # option to specify the main font of the theme
    fontFamily: "Open Sans" 

  # sidebar options
  sidebar:
    # option to specify the logo of the sidebar
    logo: "/images/refresh-square.svg"
    # option to specify the font of the sidebar
    fontFamily: "Open Sans" # "Open Sans"

  # navbar options
  navbar:
    # option to specify the logo of the sidebar
    fontFamily: "Open Sans"
  
  # 404 page options
  pagNotFound:
    # option to specify the main picture of the sidebar
    image: "/images/avataaars_404.png"
    # option to specify the title of the 404 page
    title: 404 Page Not Found :(
    # option to specify the subtitle of the 404 page
    subtitle: This is not the page you were looking for...
    # option to specify the width of the image in the 404 page
    imageWidth: 500px

  # homepage options
  homepage:
    host: http://www.farseer.vip
    # option to specify the title in the homepage
    title: Snow Wang
    # option to specify the subtitle in the homepage
    subtitle: I don't wanta be a hero, I wanta be the one sitting by the roadside and watching the hero passing by...
    # option to specify image in the homepage
    #image: "/images/avataaars.png" # worker.svg
    image: "/images/me.svg" # worker.svg
    # option to specify the width of the image in the homepage
    imageWidth: 500px

  # footer options
  footer:
    # option to specify the logo in the footer
    logo: "/images/refresh-square.svg"
    # option to specify your contact email in the footer
    email: admin@farseer.vip
    # option to specify your linkedin profile in the footer
    linkedin: https://www.linkedin.com/your_linkedin_profile/
    # option to specify the copyright in the footer
    copyright: Snow Wang - 2019
